apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: ghcr.io/jesusvillegas0/webapp:latest
        ports:
        - containerPort: 5000
      imagePullSecrets:
      - name: ghcr-secret  

