name: Deploy to Kubernetes

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to GitHub Container Registry
      run: echo ${{ secrets.GHCR_PAT }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Build and Push Docker image
      run: |
        docker build . -t ghcr.io/jesusvillegas0/webapp:latest
        docker push ghcr.io/jesusvillegas0/webapp:latest

    - name: Deploy to Kubernetes
      run: |
        kubectl set image deployment/webapp webapp=ghcr.io/jesusvillegas0/webapp:latest
